### PR TITLE
check flags for unique long/short names

### LINKED ISSUE #23: possible to register multiple flags under one shortcut
```go
f.Int("w", fStreamWidth, 1024, "the width of camera stream")
f.Int("w", "blabla", 1024, "the width of camera stream")
```

This does not fail, but probably it should?

### PR DESCRIPTION
**Pull request by skaldesh**
closes #23

### CODE REVIEW

File: flags.go [hunk 1]
```diff
@@ -78,6 +78,16 @@ func (f *Flags) register(
 		panic(fmt.Errorf("empty flag help message for flag: '%s'", long))
 	}
 
+	// Check, that both short and long are unique.
+	for _, fi := range f.list {
+		if fi.Short == short {
```
Comment (r0l1) [inline flags.go]: Short may be empty.

**Review by r0l1 — APPROVED** [review]
